#! /usr/bin/env escript
%%! -pa ./ebin/ -pa ./deps/ejson/ebin

main(Args) ->
    case Args of
        [File] -> process_it(File);
        _ -> io:format("Wrong usage: file~n", [])
    end.

process_it(File) ->
    {ok, IoDevice} = file:open(File, [read]),

    DisplayRow = fun(NewLine) ->
        io:format("NewLine: ~p~n", [NewLine])
    end,

    ecsv:process_csv_file_with(IoDevice, DisplayRow),

    ok.
